### ISSUE TITLE
OS Page Replacement

### ISSUE THREAD

**Issue by Athiban-32** [AnuragAnalog/os_assign#2]
Hii brother how to compile all the page replacement algorithms you wrote in Queue data structure.Kindly help me solve this issues @AnuragAnalog .. And I don't know how to compile all these codes..

**Comment by Athiban-32** [comment]
It is possible to write all the page replacement algorithm in a single code with queue data structure it is possible ah brother??

**Comment by AnuragAnalog** [comment]
@Athiban-32 Sorry for the delay

Can you see the make file in the memory_management directory? It has all the details of how to compile every c file and which file to link with other files.

**Comment by Athiban-32** [comment]
- @AnuragAnalog Thanks a lot. The code has runned successfully

**Comment by AnuragAnalog** [comment]
Good

**Comment by Athiban-32** [comment]
Did you know about counting semaphore in os ??did you have any code.
